import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  shikigamiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'shikigami',
    },
  ],
};

export default sidebars;
